---
include:
  # Urchin builds
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter nice_view_gem

  # Corne builds
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view

  # Crosses builds
  - board: nice_nano
    shield: crosses_left
  - board: nice_nano
    shield: crosses_right

  # Settings reset
  - board: nice_nano_v2
    shield: settings_reset
