#include "default.conf"

# Dongle is continuously USB-powered: disable deep sleep
CONFIG_ZMK_SLEEP=n

# Dongle has no display
CONFIG_ZMK_DISPLAY=n

# Query peripheral battery levels and proxy them to the host OS
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
